title: Site

fields:
  title:
    label: Admin name
    type:  text
    width: 1/2

  tagname:
    label: Appended meta title
    type:  text
    width: 1/2

  contactheading:
    label: Contact Heading
    type:  input

  contact:
    label: Contact text
    type:  textarea

  copyright:
    label: Copyright
    type:  textarea

  google:
    label: Google Anyaltic Code
    type:  textarea
